backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "blogs"
    label: "Blog Posts"
    folder: "content/blogs"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}"
    nested:
      depth: 1
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["dsa", "java-script", "system-design", "machine-learning", "ai"] }
      - { label: "Summary", name: "summary", widget: "text" }
      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["rich_text", "raw"]
        required: true

  